// Code generated by "stringer -type Type"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[FUNC-1]
	_ = x[IMPORT-2]
	_ = x[LET-3]
	_ = x[TYPE-4]
	_ = x[IF-5]
	_ = x[ELSE-6]
	_ = x[SWITCH-7]
	_ = x[AS-8]
	_ = x[LPAREN-9]
	_ = x[RPAREN-10]
	_ = x[LBRACE-11]
	_ = x[RBRACE-12]
	_ = x[LBRACKET-13]
	_ = x[RBRACKET-14]
	_ = x[SEMI-15]
	_ = x[PLUS-16]
	_ = x[MINUS-17]
	_ = x[MULT-18]
	_ = x[DIV-19]
	_ = x[PLUSASSIGN-20]
	_ = x[MINUSASSIGN-21]
	_ = x[MULTASSIGN-22]
	_ = x[DIVASSIGN-23]
	_ = x[BITNOT-24]
	_ = x[BITOR-25]
	_ = x[BITAND-26]
	_ = x[NOT-27]
	_ = x[OR-28]
	_ = x[AND-29]
	_ = x[EQUAL-30]
	_ = x[NOTEQUAL-31]
	_ = x[LT-32]
	_ = x[GT-33]
	_ = x[LE-34]
	_ = x[GE-35]
	_ = x[ASSIGN-36]
	_ = x[DOT-37]
	_ = x[PIPE-38]
	_ = x[COMMA-39]
	_ = x[LSHIFT-40]
	_ = x[RSHIFT-41]
	_ = x[IDENT-42]
	_ = x[STRING-43]
	_ = x[INT-44]
	_ = x[FLOAT-45]
}

const _Type_name = "INVALIDFUNCIMPORTLETTYPEIFELSESWITCHASLPARENRPARENLBRACERBRACELBRACKETRBRACKETSEMIPLUSMINUSMULTDIVPLUSASSIGNMINUSASSIGNMULTASSIGNDIVASSIGNBITNOTBITORBITANDNOTORANDEQUALNOTEQUALLTGTLEGEASSIGNDOTPIPECOMMALSHIFTRSHIFTIDENTSTRINGINTFLOAT"

var _Type_index = [...]uint8{0, 7, 11, 17, 20, 24, 26, 30, 36, 38, 44, 50, 56, 62, 70, 78, 82, 86, 91, 95, 98, 108, 119, 129, 138, 144, 149, 155, 158, 160, 163, 168, 176, 178, 180, 182, 184, 190, 193, 197, 202, 208, 214, 219, 225, 228, 233}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
